export const SET_THEME = 'SET_THEME';
export const TRANSITION_MODE = 'TRANSITION_MODE';
export const MUSHAF_MODE = 'MUSHAF_MODE';
export const ARABIC_FONT_SIZE = 'ARABIC_FONT_SIZE';
export const BANGLA_FONT_SIZE = 'BANGLA_FONT_SIZE';
export const ENGLISH_FONT_SIZE = 'ENGLISH_FONT_SIZE';
