export const QURAN_DATA_REQUEST = "QURAN_DATA_REQUEST";
export const QURAN_DATA_SUCCESS = "QURAN_DATA_SUCCESS";
export const QURAN_DATA_FAIL = "QURAN_DATA_FAIL";

export const SET_THEME = "SET_THEME";
export const TRANSITION_MODE = "TRANSITION_MODE";
export const MUSHAF_MODE = "MUSHAF_MODE";
export const ARABIC_FONT_SIZE = "ARABIC_FONT_SIZE";
export const BANGLA_FONT_SIZE = "BANGLA_FONT_SIZE";
export const ENGLISH_FONT_SIZE = "ENGLISH_FONT_SIZE";
